title: <p align="center"> Joaquín González </p>

logo: "images/Captura.png"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/darlin-soto-v%C3%A1squez-b97469105/">LinkedIn</a> |
  <a href="https://github.com/DarlinSoto">GitHub</a>
  </p>
  
  <p align="justify">
  Soy estudiante de ingenieria civil matematica, Chile.
  <br><br>
  Me estoy desarrollando en el ambito de analisis de datos.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
